name: Bug Report
description: Report something that isn't working as expected
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Run `ralph plan`
        2. ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages or logs if available.
    validations:
      required: true

  - type: input
    id: ralph-version
    attributes:
      label: Ralph Version
      description: Output of `ralph --version`
      placeholder: "ralph v0.1.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Output of `go version`
      placeholder: "go1.25.7 darwin/arm64"

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: "macOS 15.3 / Ubuntu 24.04"

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any relevant log output or screenshots.
      render: shell
